#list of executables to create

CXXFLAGS = -g 

BINS=pricer pricert couv test-parser delta 
pricer_SRC=montecarlo.cpp option.cpp bs.cpp barrier_l.cpp  barrier_u.cpp barrier.cpp asian.cpp basket.cpp parser.cpp typeval.cpp pricer.cpp performance.cpp
pricert_SRC=montecarlo.cpp option.cpp bs.cpp barrier_l.cpp  barrier_u.cpp barrier.cpp asian.cpp basket.cpp parser.cpp typeval.cpp performance.cpp pricert.cpp
test_parser_SRC=montecarlo.cpp option.cpp bs.cpp barrier_l.cpp  barrier_u.cpp barrier.cpp asian.cpp basket.cpp parser.cpp typeval.cpp test-parser.cpp performance.cpp
delta_SRC=montecarlo.cpp option.cpp bs.cpp barrier_l.cpp  barrier_u.cpp barrier.cpp asian.cpp basket.cpp parser.cpp typeval.cpp delta.cpp performance.cpp
couv_SRC=montecarlo.cpp option.cpp bs.cpp barrier_l.cpp  barrier_u.cpp barrier.cpp asian.cpp basket.cpp parser.cpp typeval.cpp couv.cpp performance.cpp

# This line must be the last one
include /home/perms/lelong/pnl-1.6.0/build/CMakeuser.incl
